#!/usr/bin/env python3
"""
Interactive Email Setup Script
Helps you configure email settings step-by-step
"""

import os
import sys

def create_env_file():
    """Interactively create .env file"""
    print()
    print("=" * 70)
    print("📧 INTERACTIVE EMAIL SETUP")
    print("=" * 70)
    print()
    print("This script will help you configure email settings.")
    print()
    
    # Check if .env already exists
    if os.path.exists('.env'):
        print("⚠️  .env file already exists!")
        choice = input("Do you want to overwrite it? (y/n): ").lower()
        if choice != 'y':
            print("Setup cancelled.")
            return
        print()
    
    # Provider selection
    print("Select your email provider:")
    print("1. Gmail (recommended for development)")
    print("2. Outlook/Hotmail")
    print("3. SendGrid (recommended for production)")
    print("4. Custom SMTP server")
    print()
    
    provider = input("Enter choice (1-4): ").strip()
    print()
    
    # Configure based on provider
    if provider == '1':
        # Gmail
        print("📧 GMAIL SETUP")
        print("-" * 70)
        print()
        print("Before continuing, make sure you have:")
        print("  ✓ Enabled 2-Factor Authentication on your Google account")
        print("  ✓ Generated an App Password at: https://myaccount.google.com/apppasswords")
        print()
        input("Press Enter when ready...")
        print()
        
        email = input("Enter your Gmail address: ").strip()
        app_password = input("Enter your App Password (16 characters): ").strip()
        
        config = {
            'SMTP_SERVER': 'smtp.gmail.com',
            'SMTP_PORT': '587',
            'SMTP_USERNAME': email,
            'SMTP_PASSWORD': app_password,
            'FROM_EMAIL': email,
            'APP_URL': 'http://localhost:5000',
            'DEBUG_EMAIL': 'True'
        }
        
    elif provider == '2':
        # Outlook
        print("📧 OUTLOOK/HOTMAIL SETUP")
        print("-" * 70)
        print()
        
        email = input("Enter your Outlook/Hotmail address: ").strip()
        password = input("Enter your password: ").strip()
        
        config = {
            'SMTP_SERVER': 'smtp-mail.outlook.com',
            'SMTP_PORT': '587',
            'SMTP_USERNAME': email,
            'SMTP_PASSWORD': password,
            'FROM_EMAIL': email,
            'APP_URL': 'http://localhost:5000',
            'DEBUG_EMAIL': 'True'
        }
        
    elif provider == '3':
        # SendGrid
        print("📧 SENDGRID SETUP")
        print("-" * 70)
        print()
        print("Before continuing:")
        print("  1. Sign up at https://sendgrid.com")
        print("  2. Create an API key")
        print()
        input("Press Enter when ready...")
        print()
        
        api_key = input("Enter your SendGrid API key: ").strip()
        from_email = input("Enter sender email address: ").strip()
        app_url = input("Enter your app URL (e.g., http://localhost:5000): ").strip()
        
        config = {
            'SMTP_SERVER': 'smtp.sendgrid.net',
            'SMTP_PORT': '587',
            'SMTP_USERNAME': 'apikey',
            'SMTP_PASSWORD': api_key,
            'FROM_EMAIL': from_email,
            'APP_URL': app_url,
            'DEBUG_EMAIL': 'True'
        }
        
    elif provider == '4':
        # Custom
        print("📧 CUSTOM SMTP SETUP")
        print("-" * 70)
        print()
        
        smtp_server = input("Enter SMTP server address: ").strip()
        smtp_port = input("Enter SMTP port (usually 587): ").strip() or '587'
        username = input("Enter SMTP username: ").strip()
        password = input("Enter SMTP password: ").strip()
        from_email = input("Enter sender email address: ").strip()
        app_url = input("Enter your app URL: ").strip()
        
        config = {
            'SMTP_SERVER': smtp_server,
            'SMTP_PORT': smtp_port,
            'SMTP_USERNAME': username,
            'SMTP_PASSWORD': password,
            'FROM_EMAIL': from_email,
            'APP_URL': app_url,
            'DEBUG_EMAIL': 'True'
        }
    else:
        print("Invalid choice. Setup cancelled.")
        return
    
    # Write .env file
    print()
    print("Writing .env file...")
    
    with open('.env', 'w') as f:
        f.write("# Email Configuration for Advanced Steganography App\n")
        f.write("# Generated by setup_email.py\n\n")
        for key, value in config.items():
            f.write(f"{key}={value}\n")
    
    print("✅ .env file created successfully!")
    print()
    
    # Show configuration
    print("Configuration saved:")
    print("-" * 70)
    for key, value in config.items():
        if 'PASSWORD' in key:
            display_value = '*' * len(value)
        else:
            display_value = value
        print(f"{key}={display_value}")
    print("-" * 70)
    print()
    
    # Test configuration
    print("Would you like to test this configuration now?")
    choice = input("(y/n): ").lower()
    
    if choice == 'y':
        print()
        print("Running configuration check...")
        print()
        os.system('python check_email_config.py')
    else:
        print()
        print("✅ Setup complete!")
        print()
        print("To test your configuration, run:")
        print("   python check_email_config.py")
        print()


def main():
    """Main function"""
    try:
        create_env_file()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()


if __name__ == '__main__':
    main()
